In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from scipy.special import expit
import pandas as pd
import sys
from sklearn.metrics import accuracy_score
import struct
# Load the data
data = pd.read_csv('Leases_WithDates_FixedNA.csv')

In [7]:
Month_Fixed_m = {
    '1/1/2018': 1,
    '2/1/2018': 2,
    '3/1/2018': 3,
    '4/1/2018': 4,
    '5/1/2018': 5,
    '6/1/2018': 6,
    '7/1/2018': 7,
    '8/1/2018': 8,
    '9/1/2018': 9,
    '10/1/2018': 10,
    '11/1/2018': 11,
    '12/1/2018': 12,
    '1/1/2019': 13,
    '2/1/2019': 14,
    '3/1/2019': 15,
    '4/1/2019': 16,
    '5/1/2019': 17,
    '6/1/2019': 18,
    '7/1/2019': 19,
    '8/1/2019': 20,
    '9/1/2019': 21,
    '10/1/2019': 22,
    '11/1/2019': 23,
    '12/1/2019': 24,
    '1/1/2020': 25,
    '2/1/2020': 26,
    '3/1/2020': 27,
    '4/1/2020': 28,
    '5/1/2020': 29,
    '6/1/2020': 30,
    '7/1/2020': 31,
    '8/1/2020': 32,
    '9/1/2020': 33,
    '10/1/2020': 34,
    '11/1/2020': 35,
    '12/1/2020': 36,
    '1/1/2021': 37,
    '2/1/2021': 38,
    '3/1/2021': 39,
    '4/1/2021': 40,
    '5/1/2021': 41,
    '6/1/2021': 42,
    '7/1/2021': 43,
    '8/1/2021': 44,
    '9/1/2021': 45,
    '10/1/2021': 46,
    '11/1/2021': 47,
    '12/1/2021': 48,
    '1/1/2022': 49,
    '2/1/2022': 50,
    '3/1/2022': 51,
    '4/1/2022': 52,
    '5/1/2022': 53,
    '6/1/2022': 54,
    '7/1/2022': 55,
    '8/1/2022': 56,
    '9/1/2022': 57,
    '10/1/2022': 58,
    '11/1/2022': 59,
    '12/1/2022': 60,
    '1/1/2023': 61,
    '2/1/2023': 62,
    '3/1/2023': 63,
    '4/1/2023': 64,
    '5/1/2023': 65,
    '6/1/2023': 66,
    '7/1/2023': 67,
    '8/1/2023': 68,
    '9/1/2023': 69,
    '10/1/2023': 70,
    '11/1/2023': 71,
    '12/1/2023': 72,
    '1/1/2024': 73,
    '2/1/2024': 74,
    '3/1/2024': 75,
    '4/1/2024': 76,
    '5/1/2024': 77,
    '6/1/2024': 78,
    '7/1/2024': 79,
    '8/1/2024': 80,
    '9/1/2024': 81,
    '10/1/2024': 82,
    '11/1/2024': 83,
    '12/1/2024': 84
}

Quarter_Fixed_m = {
    '3/1/2018': 1,
    '6/1/2018': 2,
    '9/1/2018': 3,
    '12/1/2018': 4,
    '3/1/2019': 5,
    '6/1/2019': 6,
    '9/1/2019': 7,
    '12/1/2019': 8,
    '3/1/2020': 9,
    '6/1/2020': 10,
    '9/1/2020': 11,
    '12/1/2020': 12,
    '3/1/2021': 13,
    '6/1/2021': 14,
    '9/1/2021': 15,
    '12/1/2021': 16,
    '3/1/2022': 17,
    '6/1/2022': 18,
    '9/1/2022': 19,
    '12/1/2022': 20,
    '3/1/2023': 21,
    '6/1/2023': 22,
    '9/1/2023': 23,
    '12/1/2023': 24,
    '3/1/2024': 25,
    '6/1/2024': 26,
    '9/1/2024': 27,
    '12/1/2024': 28,
}

CBD_suburban_m = {
    'CBD': 0,
    'Suburban': 1
}

space_type_m = {
    'Relet': 1,
    'New': 2,
    'Sublet': 3
}

transaction_type_m = {
    'Expansion': 1,
    'New': 2,
    'Relocation': 3,
    'Renewal': 4,
    'Restructure': 5,
    'Extension': 6,
    'TBD': 7,
    'Renewal and Expansion': 8,
    'Sale - Leaseback': 9
}

internal_industry_m = {
    'Financial Services and Insurance': 1,
    'Construction, Engineering and Architecture': 2,
    'Technology, Advertising, Media, and Information': 3,
    'Manufacturing (except Pharmaceutical, Retail, and Computer Tech)': 4,
    'Associations and Non-profit Organizations (except Education and Non-profit Hospitals)': 5,
    'Transportation': 6,
    'Coworking and Executive Suite Companies': 7,
    'Business, Professional, and Consulting Services (except Financial and Legal) - Including Accounting': 8,
    'Education': 9,
    'Legal Services': 10,
    'Real Estate (except coworking providers)': 11,
    'Healthcare': 12,
    'Personal Services and Recreation': 13,
    'Government': 14,
    'Retail': 15,
    'Energy & Utilities': 16,
    'TBD': 17,
    'Pharmaceuticals': 18,
    'Agriculture, Forestry, Fishing, Metal & Mineral Mining': 19,
    'Unclassifiable': 20   
}

internal_class_m = {
    'A': 1,
    'O': 0
}

market_m = {
    'Atlanta': 1,
    'Austin': 2,
    'Baltimore': 3,
    'Boston': 4,
    'Charlotte': 5,
    'Chicago': 6,   
    'Chicago Suburbs': 7,
    'Dallas/Ft Worth': 8,
    'Denver': 9,
    'Detroit': 10,
    'Houston': 11,
    'Los Angeles': 12,
    'Manhattan': 13,
    'Nashville': 14,
    'Northern New Jersey': 15,
    'Northern Virginia': 16,
    'Orange County': 17,
    'Philadelphia': 18,
    'Phoenix': 19,
    'Raleigh/Durham': 20,
    'Salt Lake City': 21,
    'San Diego': 22,
    'San Francisco': 23,
    'Seattle': 24,
    'South Bay/San Jose': 25,
    'South Florida': 26,
    'Southern Maryland': 27,
    'Tampa': 28,
    'Washington D.C.': 29
}

region_m = {
    'South': 1,
    'Northeast': 2,
    'Midwest/Central': 3,
    'West': 4
}

quarter_m = {
    'Q1': 1,
    'Q2': 2,
    'Q3': 3,
    'Q4': 4
}

state_m = {   
    'AL': 1,
    'AK': 2,
    'AZ': 3,
    'AR': 4,
    'CA': 5,
    'CO': 6,
    'CT': 7,
    'DE': 8,
    'FL': 9,
    'GA': 10,
    'HI': 11,
    'ID': 12,
    'IL': 13,
    'IN': 14,
    'IA': 15,
    'KS': 16,
    'KY': 17,
    'LA': 18,
    'ME': 19,
    'MD': 20,
    'MA': 21,
    'MI': 22,
    'MN': 23,
    'MS': 24,
    'MO': 25,
    'MT': 26,
    'NE': 27,
    'NV': 28,
    'NH': 29,
    'NJ': 30,
    'NM': 31,
    'NY': 32,
    'NC': 33,
    'ND': 34,
    'OH': 35,
    'OK': 36,
    'OR': 37,
    'PA': 38,
    'RI': 39,
    'SC': 40,
    'SD': 41,
    'TN': 42,
    'TX': 43,
    'UT': 44,
    'VT': 45,
    'VA': 46,
    'WA': 47,
    'WV': 48,
    'WI': 49,
    'WY': 50,
    'DC': 51,
    'PR': 52
}

In [8]:
data['Month_Fixed'] = data['Month_Fixed'].map(Month_Fixed_m)
data['Quarter_Fixed'] = data['Quarter_Fixed'].map(Quarter_Fixed_m)
data['CBD_suburban'] = data['CBD_suburban'].map(CBD_suburban_m)
data['space_type'] = data['space_type'].map(space_type_m)
data['transaction_type'] = data['transaction_type'].map(transaction_type_m)
data['internal_industry'] = data['internal_industry'].map(internal_industry_m)
data['internal_class'] = data['internal_class'].map(internal_class_m)
data['market'] = data['market'].map(market_m)
data['region'] = data['region'].map(region_m)
data['quarter'] = data['quarter'].map(quarter_m)
data['state'] = data['state'].map(state_m) 

del data['internal_submarket']
del data['internal_market_cluster']
del data['company_name']
del data['building_name']
del data['address']
del data['city']
data['building_id'] = data['building_id'].apply(hash)
data.dropna(inplace=True)
data.reset_index(drop=True, inplace=True)

In [9]:
from sklearn.preprocessing import StandardScaler

# Your custom list of columns to standardize
cols_to_standardize = ['leasedSF','RBA','available_space','availability_proportion','internal_class_rent', 'overall_rent',
                       'direct_available_space','direct_availability_proportion','direct_internal_class_rent',
                       'direct_overall_rent','sublet_available_space','sublet_availability_proportion',
                       'sublet_internal_class_rent','sublet_overall_rent','leasing']

scaler = StandardScaler()
data[cols_to_standardize] = scaler.fit_transform(data[cols_to_standardize])

In [10]:
data

,year,quarter,monthsigned,market,building_id,region,state,zip,internal_class,leasedSF,...,direct_availability_proportion,direct_internal_class_rent,direct_overall_rent,sublet_available_space,sublet_availability_proportion,sublet_internal_class_rent,sublet_overall_rent,leasing,Quarter_Fixed,Month_Fixed
0,2019,1,1.0,1,5898774714457520253,1,10,30303.0,1,-0.535088,...,0.263387,-0.804559,-0.982180,-0.656257,-0.634702,-0.913764,-1.078577,0.200586,5,13
1,2019,1,1.0,1,-8265971690737752617,1,10,30310.0,0,-0.460572,...,-0.832492,-1.229107,-0.982180,-1.052407,-1.402302,-1.266757,-1.078577,-0.671576,5,13
2,2019,1,1.0,1,7707337135700540400,1,10,30093.0,0,0.129168,...,-0.832492,-1.229107,-0.982180,-1.052407,-1.402302,-1.266757,-1.078577,-0.671576,5,13
3,2019,1,1.0,1,1340640927534361043,1,10,30096.0,1,0.734279,...,0.263387,-0.804559,-0.982180,-0.656257,-0.634702,-0.913764,-1.078577,0.200586,5,13
4,2019,1,1.0,1,2768342353208448425,1,10,30303.0,1,1.285603,...,0.263387,-0.804559,-0.982180,-0.656257,-0.634702,-0.913764,-1.078577,0.200586,5,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12730,2024,4,12.0,23,-5476686157416607362,4,5,94107.0,1,0.073272,...,1.782675,1.320548,0.968943,-0.180249,2.290707,1.203425,1.132349,-0.359953,28,84
12731,2024,4,12.0,24,-7491324159638064313,4,47,98004.0,1,-0.219712,...,1.324398,0.163132,-0.095684,-0.297582,0.806680,-0.092042,-0.213801,-0.760321,28,84
12732,2024,4,12.0,24,464147522397322780,4,47,98001.0,0,-0.073108,...,-0.282062,-0.555777,-0.095684,-0.799526,-0.540884,-0.370516,-0.213801,-0.906158,28,84
12733,2024,4,12.0,24,5225722779496438134,4,47,98004.0,1,-0.527151,...,1.324398,0.163132,-0.095684,-0.297582,0.806680,-0.092042,-0.213801,-0.760321,28,84
12734,2024,4,12.0,28,-3396317873297999756,1,9,33602.0,0,-0.429290,...,-0.643204,-1.003183,-0.855312,-1.059238,-0.430009,-1.026683,-0.933460,-1.011549,28,84

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12735 entries, 0 to 12734
Data columns (total 31 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   year                            12735 non-null  int64
 1   quarter                         12735 non-null  int64
 2   monthsigned                     12735 non-null  float64
 3   market                          12735 non-null  int64
 4   building_id                     12735 non-null  int64
 5   region                          12735 non-null  int64
 6   state                           12735 non-null  int64
 7   zip                             12735 non-null  float64
 8   internal_class                  12735 non-null  int64
 9   leasedSF                        12735 non-null  float64
 10  internal_industry               12735 non-null  float64
 11  transaction_type                12735 non-null  float64
 12  costarID                        12735 non-null  int64
 13  space_type                      12735 non-null  float64
 14  CBD_suburban                    12735 non-null  int64
 15  RBA                             12735 non-null  float64
 16  available_space                 12735 non-null  float64
 17  availability_proportion         12735 non-null  float64
 18  internal_class_rent             12735 non-null  float64
 19  overall_rent                    12735 non-null  float64
 20  direct_available_space          12735 non-null  float64
 21  direct_availability_proportion  12735 non-null  float64
 22  direct_internal_class_rent      12735 non-null  float64
 23  direct_overall_rent             12735 non-null  float64
 24  sublet_available_space          12735 non-null  float64
 25  sublet_availability_proportion  12735 non-null  float64
 26  sublet_internal_class_rent      12735 non-null  float64
 27  sublet_overall_rent             12735 non-null  float64
 28  leasing                         12735 non-null  float64
 29  Quarter_Fixed                   12735 non-null  int64
 30  Month_Fixed                     12735 non-null  int64
dtypes: float64(20), int64(11)
memory usage: 3.0 MB

In [13]:
data2 = pd.read_csv('Major Market Occupancy Data-revised.csv')
print(data2.describe())

              year  ending_occupancy_proportion  \
count   190.000000                   190.000000
mean   2021.894737                     0.351158
std       1.376090                     0.152696
min    2020.000000                     0.080000
25%    2021.000000                     0.220000
50%    2022.000000                     0.355000
75%    2023.000000                     0.470000
max    2024.000000                     0.660000

       starting_occupancy_proportion  avg_occupancy_proportion
count                     190.000000                190.000000
mean                        0.377895                  0.401402
std                         0.195277                  0.160338
min                         0.050000                  0.052308
25%                         0.240000                  0.284231
50%                         0.355000                  0.410385
75%                         0.450000                  0.488462
max                         0.990000                  0.838571

In [14]:
data2.head()

,year,quarter,market,ending_occupancy_proportion,starting_occupancy_proportion,avg_occupancy_proportion
0,2020,Q1,Washington D.C.,0.19,0.98,0.785714
1,2020,Q1,Manhattan,0.08,0.98,0.732857
2,2020,Q1,Chicago,0.14,0.99,0.788571
3,2020,Q1,Houston,0.33,0.99,0.835714
4,2020,Q1,Philadelphia,0.20,0.99,0.817143

In [15]:
unique = data['year'].unique()
print(unique, " ", len(unique))

[2019 2020 2021 2022 2023 2024]   6

In [53]:
summary = data.describe()
summary = summary.transpose()
# Drop only the columns you don't need for calculations
columns_to_drop = ['year','quarter', 'monthsigned', 'market', 'building_id', 'region', 'state', 'zip', 
                   'internal_class', 'leasedSF', 'internal_industry', 'transaction_type', 
                   'costarID', 'space_type', 'CBD_suburban']
summary.drop(columns_to_drop, axis=0, inplace=True)

# Ensure 'summarynont' retains necessary columns
summarynont = summary.copy()

# Transpose back for further processing
summary = summary.transpose()

# Initialize the data description DataFrame
data_des = pd.DataFrame()
data_des['Attributes'] = data.columns
data_des['Description'] = 'N/A'
data_des['Mean'] = 'N/A'
data_des['Std Deviation'] = 'N/A'
data_des['Range'] = 'N/A'
data_des['Median'] = 'N/A'

data_des['Description']= ['Year of Sale (Dropped in Model for Month,Quarter Fixed)','Quarter of Sale (Dropped in Model)',
                          'Month of Sale (Dropped in Model)','Market (One-Hot Encoded)','Building ID (Dropped in Model)',
                          'Region (Dropped in Model)','State (Dropped in Model)','Zip Code (Dropped in Model)','Quality of Building,'
                          ' Turned into boolean', 'Leased Square Footage (Standardized)','Internal Industry (One-Hot Encoded)',
                          'Transaction Type (One-Hot Encoded)','Costar ID (Dropped in Model)','Space Type (One-Hot Encoded)',
                          'CBD/Suburban (Boolean)', 'Total Leaseable Square Footage (Standardized)', 'Available Square Footage (Standardized)',
                          'Availability Proportion (Standardized)','Internal Class Rent (Standardized)','Overall Rent (Standardized)',
                          'Direct Available Square Footage (Standardized)','Direct Availability Proportion (Standardized)',
                          'Direct Internal Class Rent (Standardized)','Direct Overall Rent (Standardized)',
                          'Sublet Available Square Footage (Standardized)','Sublet Availability Proportion (Standardized)',
                          'Sublet Internal Class Rent (Standardized)','Sublet Overall Rent (Standardized)',
                          'Leasing Rate (Standardized)','Sequential Quarters','Sequential Months']
# Update the description of the data
for col in data.columns:
    if col not in columns_to_drop:  # Skip dropped columns
        if col in summarynont.index:  # Check if the column exists in summarynont
            data_des.loc[data_des['Attributes'] == col, 'Mean'] = round(data[col].mean(), 5)
            data_des.loc[data_des['Attributes'] == col, 'Std Deviation'] = round(data[col].std(), 5)
            data_des.loc[data_des['Attributes'] == col, 'Range'] = f"{round(summarynont.loc[col, 'min'], 3)}-{round(summarynont.loc[col, 'max'], 3)}"
            data_des.loc[data_des['Attributes'] == col, 'Median'] = round(data[col].median(), 5)

data_des

,Attributes,Description,Mean,Std Deviation,Range,Median
0,year,"Year of Sale (Dropped in Model for Month,Quart...",N/A,N/A,N/A,N/A
1,quarter,Quarter of Sale (Dropped in Model),N/A,N/A,N/A,N/A
2,monthsigned,Month of Sale (Dropped in Model),N/A,N/A,N/A,N/A
3,market,Market (One-Hot Encoded),N/A,N/A,N/A,N/A
4,building_id,Building ID (Dropped in Model),N/A,N/A,N/A,N/A
5,region,Region (Dropped in Model),N/A,N/A,N/A,N/A
6,state,State (Dropped in Model),N/A,N/A,N/A,N/A
7,zip,Zip Code (Dropped in Model),N/A,N/A,N/A,N/A
8,internal_class,"Quality of Building, Turned into boolean",N/A,N/A,N/A,N/A
9,leasedSF,Leased Square Footage (Standardized),N/A,N/A,N/A,N/A
10,internal_industry,Internal Industry (One-Hot Encoded),N/A,N/A,N/A,N/A
11,transaction_type,Transaction Type (One-Hot Encoded),N/A,N/A,N/A,N/A
12,costarID,Costar ID (Dropped in Model),N/A,N/A,N/A,N/A
13,space_type,Space Type (One-Hot Encoded),N/A,N/A,N/A,N/A
14,CBD_suburban,CBD/Suburban (Boolean),N/A,N/A,N/A,N/A
15,RBA,Total Leaseable Square Footage (Standardized),0.0,1.00004,-1.273-1.815,-0.23255
16,available_space,Available Square Footage (Standardized),-0.0,1.00004,-1.557-1.96,-0.09178
17,availability_proportion,Availability Proportion (Standardized),0.0,1.00004,-2.711-3.285,-0.25465
18,internal_class_rent,Internal Class Rent (Standardized),-0.0,1.00004,-1.374-2.196,-0.49657
19,overall_rent,Overall Rent (Standardized),-0.0,1.00004,-1.312-1.792,-0.44779
20,direct_available_space,Direct Available Square Footage (Standardized),-0.0,1.00004,-1.654-1.816,-0.00085
21,direct_availability_proportion,Direct Availability Proportion (Standardized),-0.0,1.00004,-1.921-2.281,-0.34682
22,direct_internal_class_rent,Direct Internal Class Rent (Standardized),0.0,1.00004,-1.331-2.148,-0.51125
23,direct_overall_rent,Direct Overall Rent (Standardized),0.0,1.00004,-1.284-1.731,-0.48029
24,sublet_available_space,Sublet Available Square Footage (Standardized),0.0,1.00004,-1.269-2.397,-0.23854
25,sublet_availability_proportion,Sublet Availability Proportion (Standardized),0.0,1.00004,-1.735-4.483,-0.14003
26,sublet_internal_class_rent,Sublet Internal Class Rent (Standardized),-0.0,1.00004,-1.578-3.037,-0.37877
27,sublet_overall_rent,Sublet Overall Rent (Standardized),0.0,1.00004,-1.445-2.703,-0.38252
28,leasing,Leasing Rate (Standardized),0.0,1.00004,-1.159-4.608,-0.2991
29,Quarter_Fixed,Sequential Quarters,17.58013,6.88658,5.0-28.0,18.0
30,Month_Fixed,Sequential Months,51.668,20.67684,13.0-84.0,53.0